import express, { Request, Response } from 'express';
import { json, urlencoded } from 'body-parser';
import cookieParser from 'cookie-parser';
import logger from 'morgan';
import helmet from 'helmet';
import { queryParser } from './middlewares';
import loginRouter from './routes/auth.route';
import UserMeRouter from './routes/user.route';
import generalRouter from './routes/general.route';
import packageRouter from './routes/package.route';
import cors from 'cors';
const app = express();
app.use(cors());
app.use(cookieParser());
app.use(json());
app.use(urlencoded({ extended: true }));
app.use(logger('dev'));
app.use(helmet());
app.use(queryParser);
app.use('/auth', loginRouter);
app.use('/packages', packageRouter);
app.use('/users', UserMeRouter);
app.use('/', generalRouter);
// app.all('*', (req: Request, res: Response) => res.status(404).send('NOT F5551OUND'));

export default app;
