export * from './appointment.service';
export * from './auth.service';
export * from './doctor.service';
export * from './package.service';
export * from './patient.service';
export * from './prescription.service';
export * from './user.service';
export * from './admin.service';
// export * from './request.service';
// export * from './contract.service';
// export * from './notification.service';
// export * from './chatroom.service';
